const artists = [
  {
    id: 1,
    name: "Ali Ahmad",
    type: "Master Weaver",
    image: "https://i.pravatar.cc/150?img=32",
    liked: true,
    rating: 4.5,
    reviewCount: 440,
    bio: "For over 35 years, Ahmad's hands have been weaving stories into fabric. Inheriting the art from his father, he specializes in the ancient, intricate patterns of 'Sussi' and 'Ajrak'. Using only natural dyes and a traditional handloom, he creates textiles that are a vibrant legacy of Sindhi culture.",
  },
  {
    id: 2,
    name: "Rao Hassan",
    type: "Ceramicist",
    image: "https://i.pravatar.cc/150?img=15",
    liked: false,
    rating: 4.2,
    reviewCount: 320,
    bio: "A master of ceramics with 20 years of experience. Rao Hassan specializes in hand-thrown pottery using traditional techniques passed down through generations.",
  },
  {
    id: 3,
    name: "Ayesha Khan",
    type: "Master Weaver",
    image: "https://i.pravatar.cc/150?img=28",
    liked: true,
    rating: 4.8,
    reviewCount: 520,
    bio: "Ayesha Khan combines traditional weaving techniques with contemporary designs. Her work reflects the rich heritage of Pakistani textile arts.",
  },
  {
    id: 4,
    name: "Umer Bashir",
    type: "Master Weaver",
    image: "https://i.pravatar.cc/150?img=45",
    liked: true,
    rating: 4.6,
    reviewCount: 380,
    bio: "With decades of experience, Umer Bashir is known for his intricate carpet designs and exceptional attention to detail.",
  },
  {
    id: 5,
    name: "Aroon",
    type: "Ceramicist",
    image: "https://i.pravatar.cc/150?img=12",
    liked: false,
    rating: 4.3,
    reviewCount: 250,
    bio: "An innovative ceramicist blending traditional and modern pottery techniques to create unique artistic pieces.",
  },
  {
    id: 6,
    name: "Abdullah Baig",
    type: "Master Cobbler",
    image: "https://i.pravatar.cc/150?img=22",
    liked: true,
    rating: 4.7,
    reviewCount: 450,
    bio: "Master cobbler Abdullah creates handcrafted shoes with exceptional precision and elegance.",
  },
  {
    id: 7,
    name: "Fatima Zahra",
    type: "Rug Maker",
    image: "https://i.pravatar.cc/150?img=35",
    liked: false,
    rating: 4.4,
    reviewCount: 290,
    bio: "Fatima Zahra specializes in traditional rug making with vibrant colors and intricate patterns.",
  },
  {
    id: 8,
    name: "Hassan Khan",
    type: "Master Carver",
    image: "https://i.pravatar.cc/150?img=50",
    liked: false,
    rating: 4.5,
    reviewCount: 360,
    bio: "Hassan Khan is renowned for his detailed wood carving and sculpture work.",
  },
  {
    id: 9,
    name: "Zainab Hussain",
    type: "Jeweler",
    image: "https://i.pravatar.cc/150?img=42",
    liked: false,
    rating: 4.6,
    reviewCount: 400,
    bio: "Zainab creates stunning handmade jewelry combining traditional craftsmanship with modern design.",
  },
];

export const artistTypes = [
  { name: "Master Weaver", count: 10 },
  { name: "Ceramicist", count: 12 },
  { name: "Master Cobbler", count: 16 },
  { name: "Rug Maker", count: 20 },
  { name: "Master Carver", count: 14 },
  { name: "Jeweler", count: 14 },
];

export const artistReviews = {
  1: [
    {
      id: 1,
      name: "David",
      location: "London",
      avatar: "https://i.pravatar.cc/45?img=32",
      date: "21 July 2025",
      rating: 4,
      text: "As a collector, I seek out authentic artisans. Khalid is a true master. The textile I acquired is not just fabric; it is a masterpiece. The craftsmanship is impeccable and the story behind it makes it priceless.",
    },
    {
      id: 2,
      name: "Fatima",
      location: "Karachi",
      avatar: "https://i.pravatar.cc/45?img=15",
      date: "20 July 2025",
      rating: 5,
      text: "Purchasing a shawl from Ahmad is like owning a piece of history. The colors are breathtaking and the geometric precision in mind-blowing. You can feel the decades of dedication in every thread.",
    },
  ],
};

export default artists;
