const products = [
  { id: 1, title: "Shawl", category: "Textiles", price: 99, image: "/images/products/shawl.png" },
  { id: 2, title: "Wool Scarf", category: "Textiles", price: 75, image: "/images/products/woolScraf.png" },
  { id: 3, title: "Cotton Fabric", category: "Textiles", price: 45,  image: "/images/products/cottonFabric.png" },
  { id: 4, title: "Silk Dupatta", category: "Textiles", price: 120,  image: "/images/products/silhDupatta.png" },
  { id: 5, title: "Pashmina Shawl", category: "Textiles", price: 150,  image: "/images/products/pashminaShawl.png" },
  { id: 6, title: "Embroidery Dress", category: "Textiles", price: 85,  image: "/images/products/embroidedDress.png" },
  { id: 7, title: "Traditional Fabric", category: "Textiles", price: 60,  image: "/images/products/TraditionalFabric.png" },
  { id: 8, title: "Handwoven", category: "Textiles", price: 110,  image: "/images/products/handwoven.png" },
  { id: 9, title: "Floral Print Cloth", category: "Textiles", price: 55,  image: "/images/products/floralDress.png" },
  { id: 10, title: "Vintage Weave", category: "Textiles", price: 95,  image: "/images/products/vintageWeave.png" },
  { id: 11, title: "Vase Set", category: "Pottery", price: 80,  image: "/images/products/vase.png" },
  { id: 12, title: "Blue Pot", category: "Pottery", price: 65,  image: "/images/products/bluePot.png" },
  { id: 13, title: "Ceramic Bowl", category: "Pottery", price: 45,  image: "/images/products/ceramicBowl.png" },
  { id: 14, title: "Clay Jar", category: "Pottery", price: 70,  image: "/images/products/clayJar.png" },
  { id: 15, title: "Decorative Plate", category: "Pottery", price: 55,  image: "/images/products/plate.png" },
  { id: 16, title: "Traditional Pot", category: "Pottery", price: 90,  image: "/images/products/TraditionalPot.png" },
  { id: 17, title: "Handmade Vase", category: "Pottery", price: 85,  image: "/images/products/HandmadeVase.png" },
  { id: 18, title: "Ceramic Dish", category: "Pottery", price: 50,  image: "/images/products/CeramicDish.png" },
  { id: 19, title: "Earthen Pot", category: "Pottery", price: 40,  image: "/images/products/EarthenPot.png" },
  { id: 20, title: "Blue Vase", category: "Pottery", price: 95,  image: "/images/products/bluevase.png" },
  { id: 23, title: "Khussa Shoes", category: "Footwear", price: 96,  image: "/images/products/khusa.jpg" },
  { id: 24, title: "Leather Sandals", category: "Footwear", price: 65,  image: "/images/products/leathershoes.png" },
  { id: 25, title: "Embroidered", category: "Footwear", price: 88,  image: "/images/products/EmbroideredShoes.png" },
  { id: 26, title: "Traditional Boots", category: "Footwear", price: 120,  image: "/images/products/TraditionalBoots.png" },
  { id: 27, title: "Casual Slippers", category: "Footwear", price: 45,  image: "/images/products/Slippers.png" },
  { id: 28, title: "Fancy Khussa", category: "Footwear", price: 105,  image: "/images/products/fancyKhusa.png" },
  { id: 29, title: "Shoes", category: "Footwear", price: 95,  image: "/images/products/Handcraftes.png" },
  { id: 30, title: "Sandals", category: "Footwear", price: 75,  image: "/images/products/Sandals.png" },
  { id: 31, title: "Shoes", category: "Footwear", price: 70,  image: "/images/products/Shoes.png"},
  { id: 32, title: "Elegant Khussas", category: "Footwear", price: 100,  image: "/images/products/ElegantKhusa.png" },
  { id: 33, title: "Silk Shoes", category: "Footwear", price: 110,  image: "/images/products/SilkShoes.png" },
  { id: 39, title: "Persian Carpet", category: "Carpets", price: 250,  image: "/images/products/PersianCarpet.png" },
  { id: 40, title: "Wool Rug", category: "Carpets", price: 180,  image: "/images/products/WoolRug.png" },
  { id: 41, title: "Traditional Carpet", category: "Carpets", price: 220,  image: "/images/products/TraditionalCarpet.png" },
  { id: 42, title: "Hand-Made Rug", category: "Carpets", price: 200,  image: "/images/products/HandknottedRug.png" },
  { id: 43, title: "Silk Carpet", category: "Carpets", price: 280,  image: "/images/products/silkCarpet.png" },
  { id: 44, title: "Kilim Rug", category: "Carpets", price: 160,  image: "/images/products/KilimRug.png" },
  { id: 45, title: "Patchwork Carpet", category: "Carpets", price: 190,  image: "/images/products/PatchworkCarpet.png" },
  { id: 46, title: "Antique Rug", category: "Carpets", price: 240,  image: "/images/products/AntiqueRug.png" },
  { id: 47, title: "Tribal Carpet", category: "Carpets", price: 210,  image: "/images/products/TribalCarpet.png" },
  { id: 48, title: "Modern Runner", category: "Carpets", price: 150,  image: "/images/products/ModernRunner.png" },
  { id: 49, title: "Turkish Rug", category: "Carpets", price: 195,  image: "/images/products/TurkishRug.png" },
  { id: 50, title: "Berber Carpet", category: "Carpets", price: 170,  image: "/images/products/BerberCarpet.png" },
  { id: 51, title: "Floral Rug", category: "Carpets", price: 205,  image: "/images/products/FloralCarpet.png" },
  { id: 52, title: "Natural Fiber Rug", category: "Carpets", price: 140,  image: "/images/products/NaturalFiberRug.png" },
  { id: 53, title: "Geometric Carpet", category: "Carpets", price: 185,  image: "/images/products/GeometricCarpet.png" },
  { id: 59, title: "Wooden Bowl", category: "Wooden Product", price: 45, image: "/images/products/WoodenBowl.png" },
  { id: 63, title: "Wooden Stool", category: "Wooden Product", price: 80, image: "/images/products/WoodenStool.png" },
  { id: 64, title: "Wooden Table", category: "Wooden Product", price: 150, image: "/images/products/Hand-carvedTable.png" },
  { id: 65, title: "Wooden Lamp", category: "Wooden Product", price: 75, image: "/images/products/WoodenLamp.png" },
  { id: 66, title: "Wood Cabinet", category: "Wooden Product", price: 120, image: "/images/products/WoodenCabinet.png" },
  { id: 68, title: "Wooden Shelf", category: "Wooden Product", price: 90, image: "/images/products/WoodenShelf.png" },
  { id: 73, title: "Earrings", category: "Jewelry", price: 80, image: "/images/products/earrings.png" },
  { id: 74, title: "Silver Necklace", category: "Jewelry", price: 95, image: "/images/products/silverNecklace.png" },
  { id: 75, title: "Bracelet Set", category: "Jewelry", price: 65, image: "/images/products/bracelet.png" },
  { id: 76, title: "Gold Pendant", category: "Jewelry", price: 120, image: "/images/products/GoldPendant.png" },
  { id: 79, title: "Traditional Set", category: "Jewelry", price: 110, image: "/images/products/TraditionalJewelry.png" },
  { id: 80, title: "Turquoise Set", category: "Jewelry", price: 75, image: "/images/products/TurquoiseSet.png" },
  { id: 81, title: "Ornamental Ring", category: "Jewelry", price: 55, image: "/images/products/OrnamentalRing.png" },
  { id: 86, title: "Ring", category: "Jewelry", price: 60, image: "/images/products/HandcraftedRing.png" }
];

export default products;
