const products = [
  // Textiles (10 items)
  { id: 1, title: "Shawl", category: "Textiles", price: 99, image: "/shawl.png" },
  { id: 2, title: "Wool Scarf", category: "Textiles", price: 75, image: "/shawl.png" },
  { id: 3, title: "Cotton Fabric", category: "Textiles", price: 45, image: "/shawl.png" },
  { id: 4, title: "Silk Dupatta", category: "Textiles", price: 120, image: "/shawl.png" },
  { id: 5, title: "Pashmina Shawl", category: "Textiles", price: 150, image: "/shawl.png" },
  { id: 6, title: "Embroidered Cloth", category: "Textiles", price: 85, image: "/shawl.png" },
  { id: 7, title: "Traditional Fabric", category: "Textiles", price: 60, image: "/shawl.png" },
  { id: 8, title: "Handwoven Textile", category: "Textiles", price: 110, image: "/shawl.png" },
  { id: 9, title: "Floral Print Cloth", category: "Textiles", price: 55, image: "/shawl.png" },
  { id: 10, title: "Vintage Weave", category: "Textiles", price: 95, image: "/shawl.png" },
  
  // Pottery (12 items)
  { id: 11, title: "Vase Set", category: "Pottery", price: 80, image: "/vase.png" },
  { id: 12, title: "Blue Pot", category: "Pottery", price: 65, image: "/vase.png" },
  { id: 13, title: "Ceramic Bowl", category: "Pottery", price: 45, image: "/vase.png" },
  { id: 14, title: "Clay Jar", category: "Pottery", price: 70, image: "/vase.png" },
  { id: 15, title: "Decorative Plate", category: "Pottery", price: 55, image: "/vase.png" },
  { id: 16, title: "Traditional Pot", category: "Pottery", price: 90, image: "/vase.png" },
  { id: 17, title: "Handmade Vase", category: "Pottery", price: 85, image: "/vase.png" },
  { id: 18, title: "Ceramic Dish", category: "Pottery", price: 50, image: "/vase.png" },
  { id: 19, title: "Earthen Pot", category: "Pottery", price: 40, image: "/vase.png" },
  { id: 20, title: "Blue Vase", category: "Pottery", price: 95, image: "/vase.png" },
  { id: 21, title: "Glazed Bowl", category: "Pottery", price: 60, image: "/vase.png" },
  { id: 22, title: "Artisan Vessel", category: "Pottery", price: 105, image: "/vase.png" },
  
  // Footwear (16 items)
  { id: 23, title: "Khussa Shoes", category: "Footwear", price: 96, image: "/khusa.jpg" },
  { id: 24, title: "Leather Sandals", category: "Footwear", price: 65, image: "/khusa.jpg" },
  { id: 25, title: "Embroidered Shoes", category: "Footwear", price: 88, image: "/khusa.jpg" },
  { id: 26, title: "Traditional Boots", category: "Footwear", price: 120, image: "/khusa.jpg" },
  { id: 27, title: "Casual Slippers", category: "Footwear", price: 45, image: "/khusa.jpg" },
  { id: 28, title: "Fancy Khussa", category: "Footwear", price: 105, image: "/khusa.jpg" },
  { id: 29, title: "Handcrafted Shoes", category: "Footwear", price: 95, image: "/khusa.jpg" },
  { id: 30, title: "Beaded Sandals", category: "Footwear", price: 75, image: "/khusa.jpg" },
  { id: 31, title: "Comfort Shoes", category: "Footwear", price: 70, image: "/khusa.jpg" },
  { id: 32, title: "Elegant Khussas", category: "Footwear", price: 100, image: "/khusa.jpg" },
  { id: 33, title: "Silk Shoes", category: "Footwear", price: 110, image: "/khusa.jpg" },
  { id: 34, title: "Decorative Shoes", category: "Footwear", price: 85, image: "/khusa.jpg" },
  { id: 35, title: "Heritage Boots", category: "Footwear", price: 130, image: "/khusa.jpg" },
  { id: 36, title: "Ethnic Shoes", category: "Footwear", price: 92, image: "/khusa.jpg" },
  { id: 37, title: "Casual Khussa", category: "Footwear", price: 80, image: "/khusa.jpg" },
  { id: 38, title: "Premium Sandals", category: "Footwear", price: 115, image: "/khusa.jpg" },
  
  // Carpets (20 items)
  { id: 39, title: "Persian Carpet", category: "Carpets", price: 250, image: "/carpet.png" },
  { id: 40, title: "Wool Rug", category: "Carpets", price: 180, image: "/carpet.png" },
  { id: 41, title: "Traditional Carpet", category: "Carpets", price: 220, image: "/carpet.png" },
  { id: 42, title: "Hand-knotted Rug", category: "Carpets", price: 200, image: "/carpet.png" },
  { id: 43, title: "Silk Carpet", category: "Carpets", price: 280, image: "/carpet.png" },
  { id: 44, title: "Kilim Rug", category: "Carpets", price: 160, image: "/carpet.png" },
  { id: 45, title: "Patchwork Carpet", category: "Carpets", price: 190, image: "/carpet.png" },
  { id: 46, title: "Antique Rug", category: "Carpets", price: 240, image: "/carpet.png" },
  { id: 47, title: "Tribal Carpet", category: "Carpets", price: 210, image: "/carpet.png" },
  { id: 48, title: "Modern Runner", category: "Carpets", price: 150, image: "/carpet.png" },
  { id: 49, title: "Turkish Rug", category: "Carpets", price: 195, image: "/carpet.png" },
  { id: 50, title: "Berber Carpet", category: "Carpets", price: 170, image: "/carpet.png" },
  { id: 51, title: "Floral Rug", category: "Carpets", price: 205, image: "/carpet.png" },
  { id: 52, title: "Natural Fiber Rug", category: "Carpets", price: 140, image: "/carpet.png" },
  { id: 53, title: "Geometric Carpet", category: "Carpets", price: 185, image: "/carpet.png" },
  { id: 54, title: "Vintage Rug", category: "Carpets", price: 230, image: "/carpet.png" },
  { id: 55, title: "Bohemian Carpet", category: "Carpets", price: 175, image: "/carpet.png" },
  { id: 56, title: "Shag Rug", category: "Carpets", price: 165, image: "/carpet.png" },
  { id: 57, title: "Contemporary Rug", category: "Carpets", price: 155, image: "/carpet.png" },
  { id: 58, title: "Premium Carpet", category: "Carpets", price: 260, image: "/carpet.png" },
  
  // Wooden Products (14 items)
  { id: 59, title: "Wooden Bowl", category: "Wooden Product", price: 45, image: "/wooden.png" },
  { id: 60, title: "Carved Box", category: "Wooden Product", price: 65, image: "/wooden.png" },
  { id: 61, title: "Wood Frame", category: "Wooden Product", price: 35, image: "/wooden.png" },
  { id: 62, title: "Decorative Stand", category: "Wooden Product", price: 55, image: "/wooden.png" },
  { id: 63, title: "Wooden Stool", category: "Wooden Product", price: 80, image: "/wooden.png" },
  { id: 64, title: "Hand-carved Table", category: "Wooden Product", price: 150, image: "/wooden.png" },
  { id: 65, title: "Wooden Lamp", category: "Wooden Product", price: 75, image: "/wooden.png" },
  { id: 66, title: "Wood Cabinet", category: "Wooden Product", price: 120, image: "/wooden.png" },
  { id: 67, title: "Carved Mirror", category: "Wooden Product", price: 70, image: "/wooden.png" },
  { id: 68, title: "Wooden Shelf", category: "Wooden Product", price: 90, image: "/wooden.png" },
  { id: 69, title: "Traditional Box", category: "Wooden Product", price: 50, image: "/wooden.png" },
  { id: 70, title: "Artistic Stand", category: "Wooden Product", price: 60, image: "/wooden.png" },
  { id: 71, title: "Wooden Tray", category: "Wooden Product", price: 40, image: "/wooden.png" },
  { id: 72, title: "Premium Cabinet", category: "Wooden Product", price: 140, image: "/wooden.png" },
  
  // Jewelry (14 items)
  { id: 73, title: "Earrings", category: "Jewelry", price: 80, image: "/earrings.png" },
  { id: 74, title: "Silver Necklace", category: "Jewelry", price: 95, image: "/earrings.png" },
  { id: 75, title: "Bracelet Set", category: "Jewelry", price: 65, image: "/earrings.png" },
  { id: 76, title: "Gold Pendant", category: "Jewelry", price: 120, image: "/earrings.png" },
  { id: 77, title: "Beaded Ring", category: "Jewelry", price: 40, image: "/earrings.png" },
  { id: 78, title: "Pearl Earrings", category: "Jewelry", price: 85, image: "/earrings.png" },
  { id: 79, title: "Traditional Jewelry", category: "Jewelry", price: 110, image: "/earrings.png" },
  { id: 80, title: "Turquoise Set", category: "Jewelry", price: 75, image: "/earrings.png" },
  { id: 81, title: "Ornamental Ring", category: "Jewelry", price: 55, image: "/earrings.png" },
  { id: 82, title: "Gemstone Jewelry", category: "Jewelry", price: 130, image: "/earrings.png" },
  { id: 83, title: "Silver Bracelet", category: "Jewelry", price: 70, image: "/earrings.png" },
  { id: 84, title: "Tribal Necklace", category: "Jewelry", price: 100, image: "/earrings.png" },
  { id: 85, title: "Elegant Pendant", category: "Jewelry", price: 90, image: "/earrings.png" },
  { id: 86, title: "Handcrafted Ring", category: "Jewelry", price: 60, image: "/earrings.png" }
];

export default products;
